# Generated by Django 5.1.2 on 2024-11-05 15:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='companyID',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='company',
            name='password',
            field=models.CharField(default='TempPass1234', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain at least one letter, one number, and be at least 8 characters.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
