# Generated by Django 5.1.2 on 2024-11-06 10:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_company_companyid_company_email_company_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(default='', max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain at least one letter, one number, and be at least 8 characters.', regex='^(?=.*[A-Za-z])(?=.*\\d)[A-Za-z\\d]{8,}$')]),
        ),
    ]
