# Generated by Django 5.1.2 on 2024-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_company_email_alter_company_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='llc_number',
            field=models.CharField(max_length=55, null=True, unique=True),
        ),
    ]
