# Generated by Django 5.1.2 on 2024-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_company_llc_number_company_llc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='LLC_Number',
            field=models.CharField(default='', max_length=55),
        ),
    ]
