# Generated by Django 5.1.2 on 2024-11-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_company_llc_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyID',
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
