# Generated by Django 5.1.2 on 2024-11-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_company_companyid_alter_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='LLC_Number',
            field=models.CharField(default='', max_length=55, unique=True),
        ),
    ]
