# Generated by Django 5.1.2 on 2024-11-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_company_llc_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='password',
            field=models.CharField(default='', max_length=128),
        ),
    ]
