# Generated by Django 5.1.2 on 2024-11-15 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_company_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyVacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('employment', models.PositiveSmallIntegerField(choices=[(0, 'intership'), (1, 'part-time job'), (2, 'full-time job')], default=0)),
                ('location', models.IntegerField()),
                ('salary', models.CharField(max_length=10)),
                ('skills', models.CharField(max_length=1000)),
                ('experience', models.IntegerField()),
                ('comment', models.CharField(max_length=1000)),
                ('is_degree_required', models.BooleanField()),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'active'), (1, 'hired'), (2, 'canceled')], default=0)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.company')),
            ],
        ),
    ]
