# Generated by Django 5.1.2 on 2024-11-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_alter_companyvacancy_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyvacancy',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='app1.company'),
        ),
    ]
