# Generated by Django 5.1.2 on 2024-11-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_alter_companyvacancy_company_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='hired_user_id',
            field=models.IntegerField(default=0),
        ),
    ]
