# Generated by Django 5.1.2 on 2024-11-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_companyvacancy_hired_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyvacancy',
            name='work_format',
            field=models.PositiveSmallIntegerField(choices=[(0, 'offline'), (1, 'gibrid'), (2, 'online')], default=0),
        ),
    ]
