# Generated by Django 5.1.2 on 2024-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_companyvacancy_work_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='LLC_Number',
            new_name='llc_number',
        ),
        migrations.AlterField(
            model_name='companyvacancy',
            name='hired_user_id',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='companyvacancy',
            name='skills',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='companyvacancy',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'active'), (1, 'hired'), (2, 'canceled')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='companyvacancy',
            name='work_format',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'offline'), (1, 'gibrid'), (2, 'online')], default=0, null=True),
        ),
    ]
