import LocationArea from "../types/location";

const locations: LocationArea[] = [
	{ value: 1, title: "Dubai International Financial Centre (DIFC)" },
	{ value: 2, title: "Business Bay, Dubai" },
	{ value: 3, title: "Dubai Media City" },
	{ value: 4, title: "Jebel Ali Free Zone" },
	{ value: 5, title: "Abu Dhabi Global Market (ADGM)" },
	{ value: 6, title: "Internet City, Dubai" },
	{ value: 7, title: "Downtown Dubai" },
	{ value: 8, title: "Dubai Silicon Oasis" },
	{ value: 9, title: "Al Quoz Industrial Area" },
	{ value: 10, title: "Sheikh Zayed Road, Dubai" },
	{ value: 11, title: "Dubai Healthcare City" },
	{ value: 12, title: "Dubai South" },
	{ value: 13, title: "Al Maryah Island, Abu Dhabi" },
	{ value: 14, title: "Al Ain" },
	{ value: 15, title: "Al Ghurair City" },
	{ value: 16, title: "Sharjah Airport International Free Zone (SAIF Zone)" },
	{ value: 17, title: "Ajman Free Zone" },
	{ value: 18, title: "Ras Al Khaimah Economic Zone (RAKEZ)" },
	{ value: 19, title: "Hamriyah Free Zone, Sharjah" },
	{ value: 20, title: "Dubai Knowledge Park" },
	{ value: 21, title: "Abu Dhabi Industrial City (ICAD)" },
	{ value: 22, title: "Dubai Production City" },
	{ value: 23, title: "Dubai Maritime City" },
	{ value: 24, title: "TwoFour54, Abu Dhabi" },
	{ value: 25, title: "Dubai Investment Park (DIP)" },
	{ value: 26, title: "Mussafah Industrial Area, Abu Dhabi" },
	{ value: 27, title: "Dubai Gold & Diamond Park" },
	{ value: 28, title: "Port Rashvalue" },
	{ value: 29, title: "Ras Al Khor Industrial Area" },
	{ value: 30, title: "Dubai Autodrome Business Park" },
	{ value: 31, title: "Emirates Industrial City, Sharjah" },
	{ value: 32, title: "Al Barsha, Dubai" },
	{ value: 33, title: "Deira, Dubai" },
	{ value: 34, title: "Dubai Creek Harbour" },
	{ value: 35, title: "Mina Zayed, Abu Dhabi" },
	{ value: 36, title: "Dubai Design District (d3)" },
	{ value: 37, title: "Dubai Science Park" },
	{ value: 38, title: "Al Mafraq Industrial Area, Abu Dhabi" },
	{ value: 39, title: "Yas Island, Abu Dhabi" },
	{ value: 40, title: "Masdar City, Abu Dhabi" },
	{ value: 41, title: "Al Khan, Sharjah" },
	{ value: 42, title: "Karama, Dubai" },
	{ value: 43, title: "Al Qusais Industrial Area, Dubai" },
	{ value: 44, title: "Jumeirah Lakes Towers (JLT), Dubai" },
	{ value: 45, title: "Al Majaz, Sharjah" },
	{ value: 46, title: "Kalba Free Zone, Sharjah" },
	{ value: 47, title: "Dubai Airport Free Zone (DAFZA)" },
	{ value: 48, title: "Al Jaddaf, Dubai" },
	{ value: 49, title: "Al Mina, Abu Dhabi" },
	{ value: 50, title: "Al Ruwais, Abu Dhabi" }
];


export default locations;