# Generated by Django 4.2.16 on 2024-11-22 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVacancyApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('message', models.TextField()),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='UserApply',
        ),
        migrations.AddField(
            model_name='userresume',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AddField(
            model_name='userresume',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userresume',
            name='is_with_degree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresume',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userresume',
            name='skills',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userresume',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uservacancyapply',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.userresume'),
        ),
        migrations.AddField(
            model_name='uservacancyapply',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
