# Generated by Django 4.2.16 on 2024-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_uservacancyapply_delete_userapply_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='experience',
            field=models.IntegerField(default=0),
        ),
    ]
